### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Geaper** [tarazansafak/ArDroneControl#2]
Hello.

How can i check if the hover is landed, hovering, etc...??

I try this and doesnt work.

if(Ar.Drone.Data.Navigation.Native.CTRL_STATES.CTRL_HOVERING)

{
//do something.
}

**Comment by tarazansafak** [comment]
Hi,

_droneClient.NavigationData.State.ToString()

this should do the trick

**Comment by Geaper** [comment]
it worked

**Comment by Geaper** [comment]
thanks
