### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by Geaper** [tarazansafak/ArDroneControl#3]
Hello again.

I wanted to change cameras but the String method isnt working for me.

if(_settings.video.channel.tostring() == "0") -> frontal camera
if(_settings.video.channel.tostring() == "1") -> inferior camera

says _settings is null.

You did the code you must know a way of changing cameras,right?

Thanks in advance.

**Comment by Geaper** [comment]
says"Field Mainform _settings" is never assigned to,, and will always have value null

**Comment by Geaper** [comment]
it's working. you need _settings = new settings();

**Comment by tarazansafak** [comment]
Check below:

```
var configuration = new Settings();
                configuration.Video.Channel = VideoChannelType.Next;
                _droneClient.Send(configuration);
```

However, this section is only for issues. You may want to take a look at the code deeply before creating issue here. Thanks.

**Comment by Geaper** [comment]
where do I ask questions? i cant pm you :(

**Comment by Geaper** [comment]
IT WORKED!!! THANKS :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
