### ISSUE TITLE
Multiple Drones

### ISSUE THREAD

**Issue by Geaper** [tarazansafak/ArDroneControl#4]
Does this library support multiple drones? If so how can I do that?

I already have a router set to 192.168.1.1 giving DHCP 192.168.1.100 and beyond.

**Comment by Geaper** [comment]
Any idea?

**Comment by Geaper** [comment]
please dont close this. this can help me and further people with the same questions. Tarazansaf can you help me? I already am connected to the drones 192.168.1.3 and .4.

How can I request info,nav data etc only drone at the time?

**Comment by Geaper** [comment]
Any idea how to custom AR.Drone ports to any number i want? I am using 2 drones and when i ask for navdata on the same port it's busy.
Is there a file on ar.drone to change this ( acessed by telnet)?

**Comment by tarazansafak** [comment]
You can check this paper. https://www.researchgate.net/publication/260420467_Hacking_and_securing_the_AR.Drone_2.0_quadcopter_-_Investigations_for_improving_the_security_of_a_toy

Basically, you can telnet the drone and change the port using the conf files which are given in the paper

**Comment by Geaper** [comment]
Thanks tarazansak but i cant seem to find the file to change the ports. I tried all with vi.

Which file is the ports? Do u know? thanks in advance

**Comment by tarazansafak** [comment]
you may ask that on there; cuz I am not sure

http://forum.developer.parrot.com/

**Comment by Geaper** [comment]
k thx

**Comment by tarazansafak** [comment]
and if you find something, it would be nice to share in here..

**Comment by Geaper** [comment]
yeah sure. i am trying but without sucess. i already created more than one drone client ,etc.. it's working if i connect one at the time atm. 

the only problem is that i cant get video even though i created other instances of the video decoder,handler,etc...  It works if I delete the decoder2 instances etc...

Maybe I can share my project here and u take a look and improve your project and mine at the same time ^^

this is a masters university project. i can add you as reference and contributor to my phD's professors. ;)

In case you want to help me.

http://www.filedropper.com/tesesdknovo

**Comment by Geaper** [comment]
I dont know if you have more than one ar.drone... mine are configured to 192.168.1.3 and .4. but you can change.

**Comment by Geaper** [comment]
tarazansak

var udpClient = new UdpClient(NavdataPort)
to

 var udpClient = new UdpClient()

And it works ;) But the label update is very slow (once a second or so). I dont know why.

**Comment by tarazansafak** [comment]
Thats cool! This month I am pretty busy and can't really take a look sorry. In the following months I may also take a loook.

**Comment by Geaper** [comment]
Ok thanks. I will be around this until July 2016 haha ^^

**Comment by Geaper** [comment]
btw tarazansak. you do have steam? or you dont play games?
